version: '3'
services:

  php-fpm:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: php-fpm
    working_dir: /var/www
    volumes:
      - ./public:/var/www
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app

  mysql:
    image: mysql:5.7.22
    volumes:
      - ./docker/mysql:/var/lib/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app

  redis:
    image: redis:7.0
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ./docker/storage/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - app

networks:
  app:
    driver: bridge
